Repository boostcampwm-2024/web29-honeyflow, pull requests merged in 2024-12, with the labels that each got.

#173 에디터 placeholder 구현
  packages/frontend/src/components/note/Editor.css
  packages/frontend/src/hooks/useMilkdownCollab.ts
  packages/frontend/src/hooks/useMilkdownEditor.ts
  packages/frontend/src/lib/milkdown-plugin-placeholder.ts
Labels: ✨ feature

#175 breadcrumb 실제 데이터 반영 (+ 로딩표시 범위 조정, copy로직 개선)
  packages/frontend/src/api/space.ts
  packages/frontend/src/components/SpaceBreadcrumb.tsx
  packages/frontend/src/components/SpaceShareAlertContent.tsx
  packages/frontend/src/components/space/SpacePageHeader.tsx
  packages/frontend/src/lib/utils.ts
  packages/frontend/src/pages/Space.tsx
Labels: 7. Subspace, ✨ feature

#177 웹소켓 연결이 https에서도 동작할 수 있도록 수정
  packages/frontend/src/api/constants.ts
  packages/frontend/src/components/note/Editor.tsx
  packages/frontend/src/hooks/yjs/useYjsConnection.tsx
Labels: 🐞 fix

#192 노드 타입 별 스타일 적용
  packages/frontend/src/components/Edge.tsx
  packages/frontend/src/components/Node.tsx
Labels: ✨ feature

#194 스페이스 표시 및 인터랙션 개선
  packages/frontend/src/components/Node.tsx
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/hooks/useDragNode.ts
Labels: 🐞 fix

#195 노드 위 우클릭시 이동모드 자동 활성화되는 오류 수정
  packages/frontend/src/hooks/useMoveNode.ts
Labels: 🐞 fix

#196 이동모드 활성화 함수에서 button 판별오류 수정
  packages/frontend/src/hooks/useMoveNode.ts
Labels: 🐞 fix

#197 인터랙션 가이드 UI 추가
  packages/frontend/package.json
  packages/frontend/src/components/space/InteractionGuide.tsx
  packages/frontend/src/components/ui/hover-card.tsx
  packages/frontend/src/pages/Space.tsx
  pnpm-lock.yaml
Labels: 🎨 UI

#199 모바일 환경에서 더보기 버튼을 통한 노드.간선 편집
  packages/frontend/src/components/Edge.tsx
  packages/frontend/src/components/Node.tsx
  packages/frontend/src/components/space/SpaceView.tsx
Labels: 🐞 fix

#203 zoom 기능 사용 시 렌더링 성능 개선
  packages/frontend/src/hooks/useZoomSpace.ts
Labels: 🛠️ refactor

#205 리드미 수정
  README.md
Labels: 📝 docs

#207 더 많은 브라우저에서 WebSocket 연결 문제가 없도록 수정
  packages/frontend/src/lib/polyfill-relative-urls-websocket.ts
  packages/frontend/src/main.tsx
Labels: 🐞 fix

#208 화면 조작 사용성 개선
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/hooks/useZoomSpace.ts
Labels: 🐞 fix, ✨ feature, 🛠️ refactor

#209 모바일 노드 진입 시 탭 이벤트 추가
  packages/frontend/src/components/Node.tsx
Labels: 🐞 fix
