Repository boostcampwm-2024/web29-honeyflow, pull requests merged in 2024-11, with the labels that each got.

#78 FE 테스트 라이브러리 설정
  packages/frontend/.gitignore
  packages/frontend/.storybook/main.ts
  packages/frontend/.storybook/preview.ts
  packages/frontend/package.json
  pnpm-lock.yaml
Labels: 1. 개발 환경 설정

#80 스타일 라이브러리 설정
  packages/frontend/.prettierrc
  packages/frontend/components.json
  packages/frontend/eslint.config.js
  packages/frontend/package.json
  packages/frontend/postcss.config.js
  packages/frontend/src/index.css
  packages/frontend/src/lib/utils.ts
  packages/frontend/tailwind.config.js
  packages/frontend/tsconfig.app.json
  packages/frontend/tsconfig.json
  packages/frontend/vite.config.ts
  pnpm-lock.yaml
Labels: 1. 개발 환경 설정

#84 블루/그린 전략으로 배포가 이루어질 수 있는 환경을 설정한다.
  .github/workflows/BACKEND_DEPLOY.yml
  .github/workflows/FRONTEND_DEPLOY.yml
  .github/workflows/REVIEW_REQUEST_ALERT.yml
  .github/workflows/reviewers.json
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierrc
  commitlint.config.mjs
  eslint.config.mjs
  package.json
  packages/backend/package.json
  packages/backend/src/app.module.ts
  packages/backend/src/chace/chace.module.ts
  packages/backend/src/chace/chace.service.spec.ts
  packages/backend/src/chace/chace.service.ts
  packages/backend/src/content/content.module.ts
  packages/backend/src/content/content.service.spec.ts
  packages/backend/src/content/content.service.ts
  packages/backend/src/context/context.module.ts
  packages/backend/src/context/context.service.spec.ts
  packages/backend/src/context/context.service.ts
  packages/backend/tsconfig.json
  pnpm-lock.yaml
  tsconfig.json
Labels: 1. 개발 환경 설정, ⚙️ setting

#83 진입 페이지 UI 구현 (스페이스 입장 동작 및 API 동작 제외)
  packages/frontend/package.json
  packages/frontend/src/App.tsx
  packages/frontend/src/components/ui/button.tsx
  packages/frontend/src/components/ui/dialog.tsx
  packages/frontend/src/components/ui/input.tsx
  packages/frontend/src/components/ui/label.tsx
  packages/frontend/src/pages/Home.tsx
  pnpm-lock.yaml
Labels: 8. Space 생성/공유, 🎨 UI

#85 Head Node UI 구현
  packages/frontend/package.json
  packages/frontend/src/App.css
  packages/frontend/src/App.tsx
  packages/frontend/src/components/space/SpaceNode.stories.tsx
  packages/frontend/src/components/space/SpaceNode.tsx
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/pages/Space.tsx
  pnpm-lock.yaml
Labels: 🎨 UI

#82 pr 리뷰 알림 발동 조건 변경
  .github/workflows/REVIEW_REQUEST_ALERT.yml
Labels: 1. 개발 환경 설정, 🐞 fix

#102 노트 노드 UI 구현
  packages/frontend/src/components/Node.tsx
  packages/frontend/src/components/space/SpaceView.tsx
Labels: 🎨 UI

#104 eslint가 예상치 못한 에러를 발생하는 문제 해결
  packages/frontend/eslint.config.js
  packages/frontend/package.json
  packages/frontend/src/App.tsx
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/components/ui/button.tsx
  packages/frontend/src/components/ui/dialog.tsx
  packages/frontend/src/components/ui/input.tsx
  packages/frontend/src/components/ui/label.tsx
  packages/frontend/src/main.tsx
  packages/frontend/src/vite-env.d.ts
  pnpm-lock.yaml
Labels: 🐞 fix

#111 docs: 인프라 아키텍처 구조 이미지 추가
  README.md
Labels: 📝 docs

#109 Edge 구현 및 노드 관련 더미 데이터 추가
  packages/frontend/package.json
  packages/frontend/src/components/Edge.tsx
  packages/frontend/src/components/Node.tsx
  packages/frontend/src/components/mock.ts
  packages/frontend/src/components/space/SpaceView.tsx
  packages/shared/types/index.ts
  pnpm-lock.yaml
Labels: 🎨 UI

#115 개발 편의를 위한 docker-compose.yml 작성
  .github/workflows/BACKEND_DEPLOY.yml
  Docker-compose.override.yml
  Docker-compose.prod.blue.yml
  Docker-compose.prod.green.yml
  Docker-compose.yml
  packages/backend/Dockerfile
  packages/backend/package.json
  packages/backend/src/main.ts
  packages/backend/src/space/dto/create.space.dto.ts
  packages/backend/src/space/dto/response.dto copy.ts
  packages/backend/src/space/dto/response.dto.ts
  packages/backend/src/space/dto/space.dto.ts
  packages/backend/src/space/space.controller.ts
  pnpm-lock.yaml
Labels: ⚙️ setting

#113 Palette 등장 시 애니메이션 표시
  packages/frontend/src/assets/react.svg
  packages/frontend/src/assets/shapes.ts
  packages/frontend/src/components/space/PaletteMenu.tsx
Labels: 5. Node 조작과 애니메이션, 🎨 UI

#118 스페이스 줌 기능 추가
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/hooks/useZoomSpace.ts
Labels: 2. Space, ✨ feature

#119 Gooey 드래그를 통한 노드 생성
  packages/frontend/package.json
  packages/frontend/src/components/Node.tsx
  packages/frontend/src/components/mock.ts
  packages/frontend/src/components/space/GooeyConnection.tsx
  packages/frontend/src/components/space/GooeyNode.tsx
  packages/frontend/src/components/space/PaletteMenu.tsx
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/hooks/useDragNode.ts
  packages/frontend/src/hooks/useSpaceElements.ts
  packages/frontend/src/lib/utils.ts
  pnpm-lock.yaml
Labels: 2. Space, ✨ feature

#123 Editor 구현 및 블록, 협업 기능 설정
  packages/frontend/.dockerignore
  packages/frontend/.prettierrc
  packages/frontend/package.json
  packages/frontend/src/App.tsx
  packages/frontend/src/components/note/Block.tsx
  packages/frontend/src/components/note/Editor.css
  packages/frontend/src/components/note/Editor.tsx
  packages/frontend/src/hooks/useMilkdownCollab.ts
  packages/frontend/src/hooks/useMilkdownEditor.ts
  packages/frontend/tailwind.config.js
  pnpm-lock.yaml
Labels: 6. Editor, ✨ feature

#121 Y.js 데이터구조에 기반한 스페이스 렌더링 구현
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/components/space/YjsSpaceView.tsx
  packages/frontend/src/hooks/useYjsSpace.tsx
  packages/frontend/src/hooks/yjs/useY.ts
  packages/frontend/src/hooks/yjs/useYjsConnection.tsx
  packages/frontend/src/lib/utils.ts
  packages/frontend/src/pages/Space.tsx
  packages/frontend/src/store/yjs.ts
  packages/shared/types/index.ts
  pnpm-lock.yaml
Labels: 2. Space, ✨ feature

#126 드래그로 노드 생성 시 yjs 데이터 생성
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/hooks/useYjsSpace.tsx
  packages/frontend/src/lib/utils.ts
  packages/shared/types/index.ts
  pnpm-lock.yaml
Labels: 3. 새로운 Node 및 Edge 생성

#129 화면 조작 후 드래그 시작노드 위치 오류 & GooeyConnection 조절점 오류 수정
  packages/frontend/src/components/space/GooeyConnection.tsx
  packages/frontend/src/components/space/GooeyNode.tsx
  packages/frontend/src/components/space/PaletteMenu.tsx
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/hooks/useDragNode.ts
  packages/frontend/src/lib/utils.ts
Labels: 🐞 fix

#137 space 생성 API V2 작업
  packages/backend/src/common/constants/error.message.constants.ts
  packages/backend/src/common/utils/socket.util.ts
  packages/backend/src/common/utils/socket.utill.spec.ts
  packages/backend/src/note/note.service.ts
  packages/backend/src/space/dto/create.space.dto.ts
  packages/backend/src/space/space.controller.ts
  packages/backend/src/space/space.module.ts
  packages/backend/src/space/space.service.ts
  packages/backend/src/space/space.validation.service.ts
  packages/backend/src/yjs/yjs.gateway.ts
  packages/frontend/src/components/note/Editor.tsx
Labels: ✨ feature

#139 Home UI 수정 및 정적 파일 추가
  packages/frontend/index.html
  packages/frontend/public/PretendardVariable.woff2
  packages/frontend/public/favicon.svg
  packages/frontend/public/home-bg.svg
  packages/frontend/public/og-image.png
  packages/frontend/public/vite.svg
  packages/frontend/src/assets/logo.svg
  packages/frontend/src/index.css
  packages/frontend/src/pages/Home.tsx
  packages/frontend/tailwind.config.js
Labels: 1. 개발 환경 설정

#132 기존 노드에 드래그 앤 드롭하여 Edge 생성
  packages/frontend/src/components/space/NearNodeIndicator.tsx
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/hooks/useDragNode.ts
  packages/frontend/src/hooks/useSpaceElements.ts
  packages/frontend/src/hooks/yjs/useYjsConnection.tsx
  packages/frontend/src/lib/utils.ts
  pnpm-lock.yaml
Labels: 3. 새로운 Node 및 Edge 생성, ✨ feature

#141 redis setting
  Docker-compose.override.yml
  packages/backend/package.json
  packages/backend/src/app.module.ts
  packages/backend/src/cache-context/cache-context.controller.spec.ts
  packages/backend/src/cache-context/cache-context.controller.ts
  packages/backend/src/cache-context/cache-context.module.ts
  packages/backend/src/cache-context/cache-context.service.spec.ts
  packages/backend/src/cache-context/cache-context.service.ts
  packages/backend/src/common/cacheConfig.service.ts
  packages/backend/src/common/logger/logger.module.ts
  packages/backend/src/redis/redis.module.ts
  packages/backend/src/redis/redis.service.spec.ts
  packages/backend/src/redis/redis.service.ts
  packages/frontend/src/components/note/Editor.tsx
  pnpm-lock.yaml
Labels: 1. 개발 환경 설정, ⚙️ setting

#147 README 메인 이미지 추가 및 테이블 수정
  README.md
Labels: 📝 docs

#143 Edge 생성 yjs와 연동 & NearNodeIndicator 개선
  packages/frontend/src/components/space/NearNodeIndicator.tsx
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/hooks/useDragNode.ts
  packages/frontend/src/hooks/useYjsSpace.tsx
Labels: 3. 새로운 Node 및 Edge 생성, 🐞 fix, 🛠️ refactor

#148 Space 생성 및 입장 FE 기능 구현 및 선택적 스페이스 데이터 모킹
  packages/backend/src/main.ts
  packages/frontend/src/api/constants.ts
  packages/frontend/src/api/http.ts
  packages/frontend/src/api/space.ts
  packages/frontend/src/hooks/useYjsSpace.tsx
  packages/frontend/src/pages/Home.tsx
Labels: 2. Space, ✨ feature

#156 FE 빌드 에러 수정
  packages/frontend/src/api/space.ts
  packages/frontend/src/pages/Home.tsx
Labels: 🐞 fix

#160 Nginx와 NextJS 간 origin 설정 충돌로 인한 CORS 에러 수정
  packages/backend/src/main.ts
  packages/frontend/nginx.conf
Labels: 🐞 fix

#144 Space 화면 Header UI 구현
  packages/frontend/package.json
  packages/frontend/src/App.tsx
  packages/frontend/src/components/SpaceBreadcrumb.tsx
  packages/frontend/src/components/space/SpacePageHeader.tsx
  packages/frontend/src/components/space/YjsSpaceView.tsx
  packages/frontend/src/components/ui/breadcrumb.tsx
  packages/frontend/src/components/ui/dropdown-menu.tsx
  packages/frontend/src/pages/Space.tsx
  pnpm-lock.yaml
Labels: 2. Space, ✨ feature

#155 스페이스에서 실시간 커서 공유 구현
  packages/frontend/src/components/PointerCursor.tsx
  packages/frontend/src/components/PointerLayer.tsx
  packages/frontend/src/components/SpaceBreadcrumb.tsx
  packages/frontend/src/components/SpaceUsersIndicator.tsx
  packages/frontend/src/components/space/SpacePageHeader.tsx
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/hooks/useYjsSpace.tsx
  packages/frontend/src/hooks/useYjsSpaceAwareness.ts
  packages/frontend/src/hooks/yjs/useYjsAwareness.ts
  packages/frontend/src/hooks/yjs/useYjsConnection.tsx
  packages/frontend/src/lib/utils.ts
  packages/shared/types/index.ts
Labels: 2. Space, ✨ feature

#157 Space에서, Subspace 생성 및 Subspace 노드 구현
  packages/frontend/src/components/Node.tsx
  packages/frontend/src/components/mock.ts
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/hooks/useAutofit.ts
  packages/frontend/src/hooks/useYjsSpace.tsx
  packages/frontend/src/hooks/yjs/useY.ts
  packages/shared/types/index.ts
Labels: 7. Subspace

#161 API 연결하여 노트 생성 및 이동
  packages/frontend/src/api/note.ts
  packages/frontend/src/components/Node.tsx
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/components/space/YjsSpaceView.tsx
  packages/frontend/src/pages/Space.tsx
Labels: 6. Editor, ✨ feature

#162 Node 이동 구현
  packages/frontend/src/components/Node.tsx
  packages/frontend/src/components/space/GooeyNode.tsx
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/hooks/useDragNode.ts
  packages/frontend/src/hooks/useMoveNode.ts
  packages/shared/types/index.ts
Labels: 5. Node 조작과 애니메이션, ✨ feature

#163 컨텍스트 메뉴를 통한 노드.간선 편집/제거
  packages/frontend/package.json
  packages/frontend/src/components/Edge.tsx
  packages/frontend/src/components/Node.tsx
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/components/space/context-menu/CustomContextMenu.tsx
  packages/frontend/src/components/space/context-menu/SpaceContextMenuWrapper.tsx
  packages/frontend/src/components/space/context-menu/type.ts
  packages/frontend/src/components/ui/context-menu.tsx
  packages/frontend/src/hooks/useDragNode.ts
  packages/frontend/src/hooks/useSpaceSelection.ts
  packages/frontend/src/hooks/useYjsSpace.tsx
  packages/frontend/src/pages/Home.tsx
  pnpm-lock.yaml
Labels: 4. Context Menu를 통한 Node 편집/제거, ✨ feature

#164 트랙패드 줌인줌아웃 방향 수정
  packages/frontend/src/hooks/useZoomSpace.ts
Labels: 2. Space, 🐞 fix

#167 prompt dialog 구현
  packages/frontend/src/App.tsx
  packages/frontend/src/components/SpaceShareAlertContent.tsx
  packages/frontend/src/components/space/PaletteMenu.tsx
  packages/frontend/src/components/space/SpacePageHeader.tsx
  packages/frontend/src/components/space/context-menu/SpaceContextMenuWrapper.tsx
  packages/frontend/src/lib/prompt-dialog.tsx
Labels: ✨ feature

#169 노드 생성 드래그 관련 버그 개선
  packages/frontend/package.json
  packages/frontend/src/components/Edge.tsx
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/hooks/useDragNode.ts
  pnpm-lock.yaml
Labels: 3. 새로운 Node 및 Edge 생성, 🐞 fix

#170 이미 연결된 노드 사이 edge 중복 생성 방지
  packages/frontend/src/hooks/useYjsSpace.tsx
Labels: 3. 새로운 Node 및 Edge 생성, 🐞 fix

#171 동시에 접속한 웹소켓 연결이 섞이는 문제 해결
  packages/backend/src/yjs/yjs.gateway.ts
Labels: 🐞 fix

#174 변경된 API, FE에 반영 및 SpaceView 사라진 코드 복구
  packages/frontend/src/api/constants.ts
  packages/frontend/src/api/note.ts
  packages/frontend/src/api/space.ts
  packages/frontend/src/components/space/SpaceView.tsx
Labels: 🐞 fix
